#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################

# See: https://github.com/certbot/certbot/issues/7873
[Service]
Environment=AWS_SHARED_CREDENTIALS_FILE=/etc/aws/ddns.credentials
Environment=AWS_PROFILE=ddns
