#!/usr/bin/env bash
set -eux

TMP_DIR=$(mktemp -d)
cd $TMP_DIR

# Yes, this is dodge
wget -O bcm2835-1.64.tar.gz https://www.airspayce.com/mikem/bcm2835/bcm2835-1.64.tar.gz
echo "06a2124cd98b4d94df25ca5d41763a3042d005545c9aca00d49bfc084809481b bcm2835-1.64.tar.gz" | sha256sum -c

tar zxvf bcm2835-1.64.tar.gz
cd bcm2835-1.64
./configure
make
make check
make install
rm -rf $TMP_DIR
