# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  external_url: "https://hass.h.wooldrige.co.uk/"

http:
  use_x_forwarded_for: true
  trusted_proxies:
   - 0.0.0.0/0
  ip_ban_enabled: false

prometheus:
  namespace: hass

alarm_control_panel:
  - platform: manual
    name: Home alarm
    unique_id: home_alarm_20250710
    code_arm_required: false
    arming_states:
      - armed_away
      - armed_night

logger:
  default: info
