#!/usr/bin/env bash
#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################
set -e

LOGFILE="/var/log/puppet-git/puppet-git-run"
function log {
    echo $(date --rfc-3339=ns)" ${1}" | tee -a $LOGFILE
}

log $0' called'

if ps -e | grep puppe[t]; then
    log 'ABORTING due to puppet already being in process list'
    exit 4;
fi

unbuffer /usr/bin/puppet apply -vv
    --modulepath=/etc/puppet-git/modules /etc/puppet-git/manifests/site.pp \
    2>&1 | tee -a $LOGFILE

log 'puppet-git-run complete'
exit 0
