#!/bin/bash
#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################
set -eu

LOGFILE="/var/log/puppet-github-update"
function log {
    echo $(date --rfc-3339=ns)" ${1}" | tee -a $LOGFILE
}

log "About to run ${0}"

cd /etc/puppet-git;

# Update main repo, check that all submodules are initialised and updated
MAIN=$(git pull)
TRIGGER=$(echo $MAIN | grep 'Already up-to-date.' | head -n 1 | sed 's/ *$//g')

git submodule init
git submodule sync
git submodule update

# Do we need to run puppet?
if [ "$TRIGGER" != "Already up-to-date." ]; then
    log "Running puppet apply"
    unbuffer /usr/bin/puppet apply \
        -vv \
        --modulepath=/etc/puppet-git/modules \
        /etc/puppet-git/manifests/site.pp \
        2>&1 | tee -a $LOGFILE
else
    log "No updates found in git pull of repo"
fi

log "${0} complete"
exit 0
