#!/bin/bash
cd /etc/puppet/git-distributed/puppet/;
NOTUPDATED=`git pull | grep 'Already up-to-date' | head -n 1 | sed 's/ *$//g'`;

if /usr/bin/[ "$NOTUPDATED" = "Already up-to-date." ]; then
    UPDATENEEDED=false
else
    UPDATENEEDED=true
fi

TIMENOW=`/bin/date`
if $UPDATENEEDED ; then
    /bin/echo $TIMENOW" - New files found from git pull, running puppet apply" >> /var/log/puppet-auto-update;
    /usr/bin/puppet apply --modulepath=/etc/puppet/git-distributed/puppet/modules /etc/puppet/git-distributed/puppet/manifests/sites.pp -vv;
else
    /bin/echo $TIMENOW" - No new files from git pull, not running puppet apply" >> /var/log/puppet-auto-update;
fi
