#!/bin/bash
#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################
#Exit if any unset variables are used, if any command returns an error
set -o nounset
set -o errexit

LOGFILE="/var/log/puppet-git/puppet-git-update"
function log {
    echo $(date --rfc-3339=ns)" ${1}"
    echo $(date --rfc-3339=ns)" ${1}" >> $LOGFILE
}

log 'puppet-git-update called'

cd /etc/puppet-git;

# Update main repo, check that all submodules are initialised and updated
MAIN=$(/usr/bin/git pull)
TRIGGER=$(/bin/echo $MAIN | /bin/grep 'Already up-to-date.' | /usr/bin/head -n 1 | /bin/sed 's/ *$//g')

/usr/bin/git submodule init
/usr/bin/git submodule sync
/usr/bin/git submodule update

# Do we need to run puppet?
if /usr/bin/[ "$TRIGGER" != "Already up-to-date." ]; then
    UPDATENEEDED=true
else
    log 'nothing found in git pull of main repo'
    UPDATENEEDED=false
fi

if $UPDATENEEDED ; then
    log 'calling puppet-git-run'
    /usr/bin/puppet-git-run
fi
log 'puppet-git-update complete'
exit 0
