#!/bin/bash
#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################
LOGFILE="/var/log/puppet-git/puppet-git-update"

/bin/echo `/bin/date`" === RUNNING puppet-git-update ===" >> $LOGFILE

cd /etc/puppet/git-distributed/puppet/;

# Update main repo, check that all submodules are initialised and updated
MAIN=`/usr/bin/git pull origin master` || exit $?
TRIGGER=`/bin/echo $MAIN | /bin/grep 'Unpacking objects' | /usr/bin/head -n 1 | /bin/sed 's/ *$//g'` || exit $?

/usr/bin/git submodule init || exit $?
/usr/bin/git submodule sync || exit $?
/usr/bin/git submodule update || exit $?

# Do we need to run puppet?
if /usr/bin/[ "$TRIGGER" = "Fast-forward" ]; then
/bin/echo `/bin/date`" - update needed, 'Unpacking objects' found in git pull" >> $LOGFILE
    UPDATENEEDED=true
else
/bin/echo `/bin/date`" - nothing found in git pull of main repo" >> $LOGFILE
    UPDATENEEDED=false
fi

if $UPDATENEEDED ; then
    /bin/echo `/bin/date`" - calling puppet-git-run" >> $LOGFILE
    /usr/bin/puppet-git-run || exit $?
fi
