#!/bin/bash
#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################
# TODO
# Improve return codes
# Add git submodule update

cd /etc/puppet/git-distributed/puppet/;
NOTUPDATED=`/usr/bin/git pull | /bin/grep 'Fast-forward' | /usr/bin/head -n 1 | /bin/sed 's/ *$//g'`;

if /usr/bin/[ "$NOTUPDATED" = "Fast-forward" ]; then
    UPDATENEEDED=true

else
    UPDATENEEDED=false
fi

TIMENOW=`/bin/date`
if $UPDATENEEDED ; then
    /bin/echo $TIMENOW" - New files found from git pull, running puppet apply" >> /var/log/puppet/git-distributed-auto-update;
    /usr/bin/puppet apply --modulepath=/etc/puppet/git-distributed/puppet/modules /etc/puppet/git-distributed/puppet/manifests/sites.pp -vv;
fi
