#!/bin/bash
FORCE="no"
[ "$1" == "-f" ] && FORCE="yes"

set -Eeuo pipefail
source /usr/share/wpu/wpu_shell
trap escalate_if_anything_fails ERR


# Config
GDIR="/etc/gdpup"

# Runtime flags
GIT_REMOTE_CHANGES="no"

# -----------
#
#
if [ "$FORCE" == "no" ] && ! is_toggle_on "enabled_gdpup"; then
    log "gdpup disabled via /etc/toggles.toml"
    exit 0
fi

if [ ! -f "$GDIR/manifests/nodes.pp" ]; then
    log "Cloning repo to ${GDIR}."
    rm -rf "$GDIR"
    git clone --depth=1 https://github.com/AWooldrige/puppet.git "$GDIR"
    GIT_REMOTE_CHANGES="yes"
fi

cd "$GDIR"

if [ "$(git diff-index --exit-code --quiet HEAD)" ]; then
    log "Local git changes to ${GDIR}, Aborting."
    exit 1
fi

if [ "$GIT_REMOTE_CHANGES" == "no" ]; then
    log "Checking git remote for repo changes"
    OLD_HEAD=$(cat "$GDIR/.git/refs/heads/master")
    git pull
    NEW_HEAD=$(cat "$GDIR/.git/refs/heads/master")
    if [ "$OLD_HEAD" != "$NEW_HEAD" ]; then
        log " -> Updated to $NEW_HEAD"
        GIT_REMOTE_CHANGES="yes"
    else
        log " -> No updates available"
    fi
fi

if [ "$FORCE" == "no" ] && [ "$GIT_REMOTE_CHANGES" == "no" ]; then
    log "No changes, not running puppet apply."
    exit 0
fi

log "Running puppet apply"
puppet apply -v --strict_variables "--modulepath=/etc/puppet/code/modules/:/etc/securepuppet/modules/:${GDIR}/modules" "${GDIR}/manifests"
