#!/usr/bin/env python
from boto.ec2.connection import EC2Connection
from boto.utils import get_instance_metadata, get_instance_userdata

from woolielibs.loghelper import bootstrap_logger
from socket import inet_aton

l = bootstrap_logger("Associate_EIP_With_Self")

if __name__ == "__main__":

    meta = get_instance_metadata(timeout=2, num_retries=2)
    try:
        this_instance = meta["instance-id"]
        current_ip = meta["public-ipv4"]
    except KeyError, e:
        l.exception("This script doesn't seem to be on an EC2 instance. "
            "It wasn't possible to get the instance metadata")
        raise SystemExit(1)

    try:
        #This is instead of matching against a regex - see:
        #http://stackoverflow.com/questions/10086572
        eip = get_instance_userdata()
        inet_aton(eip)
    except:
        l.exception("UserData for this instance doesn't seem to be an IP: "
            "nothing to associate!")
        raise SystemExit(1)

    if eip != current_ip:
        l.info("Associating EIP {0} with this instance ({1})".format(
            eip, this_instance))
        result = EC2Connection().associate_address(this_instance, eip)
        l.info("Done. {0} now associated with ({1}).".format(
            eip, this_instance))
    else:
        l.info("EIP {0} already associated with this instance ({1})".format(
            eip, this_instance))
