#!/bin/bash
#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################

# Adapted from:
# http://serverfault.com/questions/353153/managing-service-passwords-with-puppet

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <pwd_name>"
    exit 1
fi

if [ ! -x /usr/bin/pwgen ]; then
    echo "missing pwgen!" >&2
    exit 1
fi

get_name="$1"

workdir="/root/extlookup"
workfile="$workdir/passwd"

if [ ! -e $workfile ]; then
    touch $workfile
    chmod 400 $workfile
    chown root:root $workfile
fi

if [ ! -r $workfile ]; then
    echo "no read permission on password file: $workfile"
    exit 2
fi

# get password from storage
pwd=$(awk -F: -v name="$get_name" '
BEGIN      { r = "NOTFOUND" }
name == $1 { r = $2         }
END        { printf "%s", r }
' "$workfile")

if [ "$pwd" = "NOTFOUND" ]; then
    # generate new password & store it
    len=$((60 + $RANDOM % 9 ))
    pwd=$(/usr/bin/pwgen -s $len 1)

    echo "${get_name}:${pwd}" >> $workfile
fi

# echo password (without new line)
echo -n "$pwd"
