#!/bin/bash
#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################

info="[INFO] "
error="[ERROR] "
usage="Usage: $0 <push|pull> [from_hostname]"

if /usr/bin/[ "$#" -lt 1 ] || /usr/bin/[ "$#" -gt 2 ]; then
    /bin/echo "ERROR: Invalid number of arguments"
    /bin/echo $usage
    exit 1
fi

action=$1
hostname=$(hostname -s)
bkp_location=/bkps-incremental

if /usr/bin/[ -z $hostname ]; then
    /bin/echo $error"Hostname (found by 'hostname -s') cannot be empty"
    exit 1
fi
if /usr/bin/[ ! -d $bkp_location ]; then
    /bin/echo $error"Backup location '"$bkp_location"' doesn't exists"
    exit 1
fi

if /usr/bin/[ $action = "push" ]; then
    if /usr/bin/[ "$#" -gt 1 ]; then
        /bin/echo $error"Too many arguments"
        /bin/echo $usage
        exit 1
    fi

    echo $info"=== Pushing backups ("$bkp_location") for "$hostname" ==="


    echo $info"Sending with rdiff-backup"
    /usr/bin/rdiff-backup \
        --create-full-path --force --exclude-special-files --no-acls --no-eas \
        $bkp_location backupoutgoing::./$hostname/ || exit 3

    echo $info"Cleaning up backup revision history older than 2 weeks"
    /usr/bin/rdiff-backup --remove-older-than 2W backupoutgoing::./$hostname/ || exit 3

    exit 0
fi

if /usr/bin/[ $action = "pull" ]; then
    # Allow the hostname to grab backups from to be overridden.
    from_hostname=$hostname
    /usr/bin/[ "$#" -eq 2 ] && from_hostname=$2

    echo $info"=== Pulling backups into "$bkp_location" from "$from_hostname" backups ==="

    echo $info"Cleaning out $bkp_location directory"
    rm -rf $bkp_location/*

    echo $info"Retrieving with rdiff-backup"
    /usr/bin/rdiff-backup -r now \
        --exclude-special-files --no-acls --no-eas \
        backupoutgoing::./$from_hostname/ $bkp_location/ || exit 3

    exit 0
fi

echo $usage
exit 1
