#!/bin/bash
#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################

# Adapted from:
# http://serverfault.com/questions/353153/managing-service-passwords-with-puppet

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <push|pull> [from_hostname]"
    exit 1
fi

action="$1"

if /usr/bin/[ $action = "push" ]; then
    echo $info"=== Pushing backups ==="

    echo $info"Cleaning out backups directory "$backup_path
    /bin/rm -rf $backup_path
    /bin/mkdir -p $backup_path

    echo $info"Creating hardling mirror of "$uploads_path
    /bin/cp -al $uploads_path $backup_path

    echo $info"Dumping MySQL database "$wp_id
    /usr/bin/mysqldump $wp_id > $backup_path"/"$wp_id".sql"
    exit 0
fi

if /usr/bin/[ $action = "pull" ]; then
    from_hostname="$2"
    echo $info"=== Generating Backup for "$wp_id" ==="

    echo $info"Cleaning out backups directory "$backup_path
    /bin/rm -rf $backup_path
    /bin/mkdir -p $backup_path

    echo $info"Creating hardling mirror of "$uploads_path
    /bin/cp -al $uploads_path $backup_path

    echo $info"Dumping MySQL database "$wp_id
    /usr/bin/mysqldump $wp_id > $backup_path"/"$wp_id".sql"
    exit 0
fi


exit 1
