name    'awooldrige-wordpress'
version '0.0.1'
source 'git://github.com/AWooldrige/puppet.git'
author 'Alistair Wooldrige'
license 'Apache2'
summary 'Tool to manage WordPress instances.'
description "Tool to manage WordPress instances. Doesn't take responsibility for httpd, this is assumed installed."
project_page 'http://github.com/AWooldrige/puppet'

## Add dependencies, if any:
dependency 'puppetlabs/mysql', '>= 0.1.0'
