#!/usr/bin/env bash
#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################

#Exit if any unset variables are used, if any command returns an error
set -o nounset
set -o errexit

info="[INFO] "
error="[ERROR] "
usage="Usage: $0 <backup|restore> <incremental|full> <wordpress_instance_identifier>"

if /usr/bin/[ "$#" -ne 3 ]; then
    /bin/echo $usage
    exit 1
fi

action="$1"
packaging="$2"
wp_id="$3"
wp_path="/var/www/"$wp_id
wpcontent_path=$wp_path"/wp-content"
uploads_path=$wpcontent_path"/uploads"
backup_path="/bkps-incremental/wordpress/"$wp_id
full_backup_path="/bkps-full/wordpress"

if /usr/bin/[ ! -d $wpcontent_path ]; then
    /bin/echo "WordPress id $wp_id doesn't exist. Couldn't find $wp_path"
    exit 2
fi


if /usr/bin/[ $action = "backup" ]; then
    echo $info"=== Generating Backup for "$wp_id" ==="

    echo $info"Cleaning out backups directory "$backup_path
    /bin/rm -rf $backup_path
    /bin/mkdir -p $backup_path

    echo $info"Creating hardlink mirror of "$uploads_path
    /bin/cp -al $uploads_path $backup_path || \
        { echo $error"Could not find wp-content/uploads"; exit 1; }

    echo $info"Dumping MySQL database "$wp_id
    /usr/bin/mysqldump $wp_id > $backup_path"/"$wp_id".sql"

    echo $info"Removing resized images from backup"
    /usr/bin/find $backup_path/uploads/ -regextype sed -regex ".*/.*[0-9]\+x[0-9]\+\..*" -delete

    if /usr/bin/[ $packaging = "full" ]; then
        /bin/mkdir -p $full_backup_path

        echo $info"Creating full backup within "$full_backup_path
        /bin/tar -czf $full_backup_path"/"$wp_id".tar.gz" -C $backup_path .
    fi
    exit 0
fi

if /usr/bin/[ $action = "restore" ]; then
    echo $info"=== Restoring Backup for "$wp_id" ==="

    if /usr/bin/[ $packaging = "full" ]; then
        echo $info"Extracting full backup into incremental backup dir"
        /bin/rm -rf $backup_path
        /bin/mkdir -p $backup_path
        /bin/tar -zxf $full_backup_path"/"$wp_id".tar.gz" -C $backup_path
    fi

    echo $info"Cleaning out uploads directory "$uploads_path
    /bin/rm -rf $uploads_path

    echo $info"Copying files from "$backup_path" to "$uploads_path
    /bin/cp -al $backup_path/uploads $wpcontent_path

    echo $info"Dropping any tables currently in the database"
    /usr/bin/mysqldump --no-data --add-drop-table $wp_id | \
        /bin/grep ^DROP | /usr/bin/mysql $wp_id

    echo $info"Restoring database"
    /usr/bin/mysql $wp_id < $backup_path"/"$wp_id".sql"

    echo $info"Generating thumbnails"
    /usr/bin/wp thumbnails generate --path=$wp_path

    exit 0
fi

/bin/echo $error"Action needs to be either 'backup' or 'restore'"
/bin/echo $usage
exit 1
