#!/usr/bin/python
import sys
import os
import socket

# Width of terminal
TERM_WIDTH = 80
SURROUND = '#'


def print_s(text):
    print SURROUND + text.center(TERM_WIDTH - 2, ' ') + SURROUND


print SURROUND * TERM_WIDTH

print_s("Welcome to %s" % socket.gethostname())

print SURROUND * TERM_WIDTH
