#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################

location = /kitchen/envelopes.json {
    if ($kitchen_data_allowed != 1) {
        return 403;
    }

    alias /srv/kitchen/envelopes.json;
    default_type application/json;
    add_header Cache-Control "no-store" always;
}
