#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################

[Service]
CPUQuota=25%
MemoryAccounting=true
MemoryHigh=100M
MemoryMax=160M
TasksMax=32
