###############################################################################
# All of these are blocking operations (prompt won't appear before)
###############################################################################
set -o vi
export EDITOR=vim
