#!/usr/bin/env python
from subprocess import check_output, CalledProcessError, STDOUT
import argparse
import os
from woolielibs.loghelper import bootstrap_logger
from logging import getLogger

LOGGER_NAME = "Nanoc_Site_Downloader"

def scall(cmd):
    l = getLogger(LOGGER_NAME)
    l.debug(cmd)
    try:
        stdout = check_output(cmd, stderr=STDOUT, shell=True)
    except CalledProcessError, e:
        l.error(e.output)
        raise e
    if stdout:
        l.debug(stdout)

def file_contents(file):
    with open(file) as f:
        return f.read()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("domain", help="domain for the site")
    parser.add_argument("repo", help="git repo where the " +
        "nanoc-site-downloader will download and install from")
    args = parser.parse_args()

    l = bootstrap_logger(LOGGER_NAME)

    all_checkouts = "/var/nanoc/repos"
    if not os.path.exists(all_checkouts):
        scall("mkdir {0} && chmod 755 {0}".format(all_checkouts))

    checkout = "{0}/{1}".format(all_checkouts, args.domain)

    rebuild = False
    if os.path.exists(checkout):
        ref_file = ".git/refs/heads/master"
        before = file_contents("{0}/{1}".format(checkout, ref_file))
        scall("(cd {} && git pull)".format(checkout))
        after = file_contents("{0}/{1}".format(checkout, ref_file))
        if before != after:
            rebuild = True
    else:
        scall("git clone {0} {1}".format(args.repo, checkout))
        rebuild = True

    if rebuild:
        scall("nh install -p {0}".format(checkout))
