#!/usr/bin/env python
from subprocess import check_call, CalledProcessError
import argparse

def scall(cmd):
    print cmd
    check_call(cmd, shell=True)

def make_prepare(path):
    scall("mkdir {0}/SOURCES".format(path))

def make_clean(path):
    scall("rm -rf {0}/SOURCES".format(path))

def make_build(path):
    make_clean(path)
    make_prepare(path)
    scall("(cd {0} && nanoc compile".format(path))



def parse_nanoc_config_yaml(path):
    with open(path+"/nanoc.yaml") as file:
        foo = yaml.safe_load(f)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("instruction",
                        choices=["build", "deb", "install", "clean"],
                        help="what the nanoc helper should do")
    parser.add_argument("path", default=".",
                        help="path to compile with nanoc")
    args = parser.parse_args()

    path = args.path.rstrip('/')


    try:
        scall("ls {0}/nanoc.yaml".format(args.path))
    except CalledProcessError:
        raise Exception (
            "'{0}' doesn't seem to be a nanoc site path".format(path))


    if args.instruction == "build":
        make_build(args.path)

    if args.instruction == "clean":
        make_clean(args.path)
