#########################################################################
##   This file is controlled by Puppet - changes will be overwritten   ##
#########################################################################

location /tw/ww {
    # See conf.d/client-authorisation.conf
    if ($wiki_allowed != 1) {
        return 403;
    }

    proxy_pass http://127.0.0.1:8115;
}
